export const filterData = [
  { name: 'Burgers', image: require('../assets/burger.jpg'), id: '1' },
  { name: 'Sandwich', image: require('../assets/sandwich.jpg'), id: '2' },
  { name: 'Salads', image: require('../assets/salad.jpg'), id: '3' },
  { name: 'Tacos', image: require('../assets/tacos.jpg'), id: '4' },
  { name: 'Italian', image: require('../assets/italian.jpeg'), id: '5' },
  { name: 'Plates grille', image: require('../assets/grillee.jpg'), id: '6' },
  { name: 'Deserts', image: require('../assets/desserts.jpg'), id: '7' },
];

export const restaurantsData = [
  {
    restaurantName: 'Dallas restaurant',
    farAway: '21.2',
    businessAddress: '114 haysafa boulvard: chaouki benimellal ',
    images: require('../assets/dallas.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: { lat: -26.1888612, lng: 28.246325 },
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'American cuisine...',
    productData: [
      {
        name: 'burger',
        price: 28,
        image: require('../assets/burger.jpg'),
      },
      {
        name: 'chicken strips',
        price: 24,
        image: require('../assets/14.jpg'),
      },
      {
        name: 'Millanaise',
        price: 39,
        image: require('../assets/millanaise.jpg'),
      },
    ],

    Sandwiches: [
      {
        name: 'Viande hachee sandwich',
        price: 22,
        image: require('../assets/kafta.jpg'),
        details: 'Viande hachee avec des frites, tomate, onion et lettuce',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 10,
      },
      {
        name: 'Saussice sandwich',
        price: 15,
        image: require('../assets/sas.jpg'),
        details: 'Saussice avec des frites, tomate, onion et lettuce',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 11,
      },
      {
        name: 'Steak sandwich',
        price: 25,
        image: require('../assets/steak1.jpg'),
        details: '',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 12,
      },
      {
        name: 'Dinde sandwich',
        price: 22,
        image: require('../assets/dind.jpg'),
        details: '',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 13,
      },
      {
        name: 'calamar et crevette sandwich',
        price: 27,
        image: require('../assets/cal.jpg'),
        details: '',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 14,
      },
      {
        name: 'filet de poisson sandwich',
        price: 27,
        image: require('../assets/fish.jpg'),
        details: '',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 15,
      },
      {
        name: 'millanaise sandwich',
        price: 28,
        image: require('../assets/6.jpg'),
        details: '',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 16,
      },
      {
        name: 'Meatball sandwich',
        price: 28,
        image: require('../assets/balls.jpg'),
        details: '',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 17,
      },
    ],
    Burgers: [
      {
        name: 'cheeseburger',
        price: 28,
        image: require('../assets/1.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 21,
      },
      {
        name: 'Double cheeseburger',
        price: 35,
        image: require('../assets/22.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 22,
      },
      {
        name: 'Grilled chicken burger',
        price: 27,
        image: require('../assets/3.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 23,
      },
      {
        name: 'Fried chicken burger',
        price: 28,
        image: require('../assets/4.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 24,
      },
      {
        name: 'Double grilled chicken burger',
        price: 35,
        image: require('../assets/double4.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 25,
      },
      {
        name: 'Double fried chicken burger',
        price: 35,
        image: require('../assets/double3.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 26,
      },
    ],
    Tacos: [
      {
        name: 'Taco poulet grille',
        price: 30,
        image: require('../assets/taco-poulet.jpeg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 41,
      },
      {
        name: 'Taco poulet chawarma',
        price: 30,
        image: require('../assets/taco-chawarma.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 42,
      },
      {
        name: 'Taco Viande hachee',
        price: 30,
        image: require('../assets/taco-kafta.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 43,
      },
      {
        name: 'Taco chichen strips',
        price: 30,
        image: require('../assets/taco chicken.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 44,
      },
      {
        name: 'Taco mixte',
        price: 35,
        image: require('../assets/tacos-mixte.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 45,
      },
      {
        name: 'Tacos Saucisse',
        price: 30,
        image: require('../assets/taco-saucisse.png'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 46,
      },
    ],
    Salads: [
      {
        name: 'Salad nicoise',
        price: 19,
        image: require('../assets/saladnicoise.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 51,
      },
      {
        name: 'House salad',
        price: 19,
        image: require('../assets/salad.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 52,
      },
      {
        name: 'Salad marocain',
        price: 10,
        image: require('../assets/salad-marocain.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 53,
      },
      {
        name: 'Salad nicoise au thon',
        price: 25,
        image: require('../assets/salad-thon.jpeg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 54,
      },
    ],
    Plate: [
      {
        name: 'Shish Kebob',
        price: 35,
        image: require('../assets/kebob.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 61,
      },
      {
        name: 'Brouchete de dinde',
        price: 37,
        image: require('../assets/brochettedinde.jpeg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 62,
      },
      {
        name: 'Brouchete de boeuf',
        price: 42,
        image: require('../assets/brochetteboeuf.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 63,
      },
      {
        name: 'Steak de poulet',
        price: 37,
        image: require('../assets/salad-thon.jpeg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 64,
      },
      {
        name: 'Filet de poisson',
        price: 35,
        image: require('../assets/filetpoisson.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 65,
      },
      {
        name: 'Plat Mixte',
        price: 45,
        image: require('../assets/platmixte.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 0, checked: false, id: 0 },
            { name: 'Avec Legume', price: 0, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 0, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 0, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],

          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 66,
      },
    ],
    Italian: [
      {
        name: 'Chicken strips plate',
        price: 14,
        image: require('../assets/14.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],

          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 81,
      },
      {
        name: 'Friture de fruit de mer',
        price: 49,
        image: require('../assets/friture.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],

          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 82,
      },
      {
        name: 'Chicken strips plate',
        price: 14,
        image: require('../assets/14.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],

          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 83,
      },
      {
        name: 'Spaghetti bolognaise',
        price: 35,
        image: require('../assets/14.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [],
        preferenceData: [],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 84,
      },
      {
        name: 'Spaghetti fruit de mer',
        price: 35,
        image: require('../assets/spaghettifruit.jpg'),
        details: 'wwwwwwwwwwwwwww',
        preferenceTitle: [],
        preferenceData: [],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 85,
      },
    ],
    Pizza: [
      {
        name: 'Pizza poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 1000001,
      },
    ],
    Desserts: [
      {
        name: 'keylime pie',
        price: 15,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 10000001,
      },
    ],
    Drinks: [
      {
        name: 'Soda',
        price: 10,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 100000001,
      },
    ],

    id: 0,
  },

  {
    restaurantName: 'Gardala',
    farAway: '12.7',
    businessAddress: '22 Bessie street, Cape Town',
    images: require('../assets/Gardalla.jpg'),
    averageReview: 4.3,
    numberOfReview: 306,
    coordinates: { lat: -26.1891648, lng: 28.2441808 },
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: 'Chicken,Chicken wings... ',
    productData: [
      {
        name: 'Coscous',
        price: 29.3,
        image: require('../assets/coscous.jpg'),
      },
      {
        name: 'Salad',
        price: 50.8,
        image: require('../assets/saladh.jpg'),
      },
      {
        name: 'Creeps',
        price: 70,
        image: require('../assets/Creeps.jpg'),
      },
    ],

    Sandwiches: [
      {
        name: 'dinde sandwich',
        price: 22,
        image: require('../assets/burger.jpg'),
        details: 'dididididididididi',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],

          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 0,
      },
    ],
    Burgers: [
      {
        name: 'cheeseburger',
        price: 28,
        image: require('../assets/burger.jpg'),
        details: 'ffffffffffffffffffffff',
        id: 0,
      },
    ],
    Tacos: [
      {
        name: 'tacos poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'popopopopiopikp',
        id: 0,
      },
    ],
    Salads: [
      {
        name: 'salade nicoise',
        price: 19,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Plate: [
      {
        name: 'Plate Mixte',
        price: 45,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Italian: [
      {
        name: 'Spaghetti',
        price: 35,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Pizza: [
      {
        name: 'Pizza poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Desserts: [
      {
        name: 'keylime pie',
        price: 15,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Drinks: [
      {
        name: 'Soda',
        price: 10,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    id: 1,
  },

  {
    restaurantName: 'Sydney',
    farAway: '5',
    businessAddress: ' 17 Olivia Rd, Johannesburg',
    images: require('../assets/sydney.jpg'),
    coordinates: { lat: -26.1886781, lng: 28.244879 },
    averageReview: 4.9,
    numberOfReview: 1272,
    discount: 12,
    deliveryTime: 25,
    collectTime: 15,
    foodType: 'Flame grilled beef Burgers',
    productData: [
      {
        name: 'Coscous',
        price: 29.3,
        image: require('../assets/coscous.jpg'),
      },
      {
        name: 'Salad',
        price: 50.8,
        image: require('../assets/saladh.jpg'),
      },
      {
        name: 'Creeps',
        price: 70,
        image: require('../assets/Creeps.jpg'),
      },
    ],

    Sandwiches: [
      {
        name: 'Viande hachee sandwich',
        price: 22,
        image: require('../assets/burger.jpg'),
        details: 'DDFFFFDDFFFFFG',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],

          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 0,
      },
      {
        name: 'Saussice sandwich',
        price: 15,
        image: require('../assets/burger.jpg'),
        details: 'DDFFFFDDFFFFFG',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],

          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 1,
      },
      {
        name: 'Millanaise sandwich',
        price: 22,
        image: require('../assets/burger.jpg'),
        details: 'DDFFFFDDFFFFFG',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 2,
      },
      {
        name: 'Mixte sandwich',
        price: 27,
        image: require('../assets/burger.jpg'),
        details: 'DDFFFFDDFFFFFG',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 3,
      },
    ],
    Burgers: [
      {
        name: 'cheeseburger',
        price: 28,
        image: require('../assets/burger.jpg'),
        details: 'ftftftftftftftf',
        id: 0,
      },
    ],
    Tacos: [
      {
        name: 'tacos poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'ghthgthkhkhkhkjh',
        id: 0,
      },
    ],
    Salads: [
      {
        name: 'salade nicoise',
        price: 19,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Plate: [
      {
        name: 'Plat Mixte',
        price: 45,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Italian: [
      {
        name: 'Spaghetti',
        price: 35,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Pizza: [
      {
        name: 'Pizza poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Desserts: [
      {
        name: 'keylime pie',
        price: 15,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Drinks: [
      {
        name: 'Soda',
        price: 10,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],

    id: 2,
  },

  {
    restaurantName: 'La rouche',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images: require('../assets/rouche.jpg'),
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: { lat: -26.1845336, lng: 28.2481691 },
    discount: null,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Tacos',
        price: 29.3,
        image: require('../assets/coscous.jpg'),
      },
      {
        name: 'tagine',
        price: 50.8,
        image: require('../assets/saladh.jpg'),
      },
      {
        name: 'Creeps',
        price: 70,
        image: require('../assets/Creeps.jpg'),
      },
    ],

    Sandwiches: [
      {
        name: 'Friut de mer sandwich',
        price: 22,
        image: require('../assets/burger.jpg'),
        details: ' poiuytrewq',
        preferenceTitle: [
          'Would you like no fries and add a side?',
          'Would you like to add a side?',
          'Would you Like any extra sauce?',
        ],
        preferenceData: [
          [
            { name: 'Avec pure', price: 3, checked: false, id: 0 },
            { name: 'Avec Legume', price: 3, checked: false, id: 1 },
            { name: 'Avec Spaghetti', price: 3, checked: false, id: 2 },
            { name: 'Avec Penne pasta', price: 3, checked: false, id: 3 },
            { name: 'Avec salade', price: 3, checked: false, id: 4 },
            { name: 'Avec riz', price: 3, checked: false, id: 5 },
          ],
          [
            { name: 'Sans tomate', price: 0, checked: false, id: 0 },
            { name: 'Sans onion', price: 0, checked: false, id: 1 },
            { name: 'Sans lettuce', price: 0, checked: false, id: 2 },
            { name: 'Sans mayonaise', price: 0, checked: false, id: 3 },
            { name: 'Sans fromage', price: 0, checked: false, id: 4 },
            { name: 'Sans frites ', price: 0, checked: false, id: 5 },
          ],
          [
            { name: 'Algerian sauce', price: 2, checked: false, id: 0 },
            { name: 'Bigup Sauce', price: 2, checked: false, id: 1 },
            { name: 'Andalous Sauce', price: 2, checked: false, id: 2 },
          ],
        ],
        minimum_quatity: [2, 1, 2, null, null],
        counter: [0, 0, 0, 0, 0],
        required: [true, true, true, false, false],
        id: 0,
      },
    ],
    Burgers: [
      {
        name: 'cheeseburger',
        price: 28,
        image: require('../assets/burger.jpg'),
        details: '35353645343243ddfff',
        id: 0,
      },
    ],
    Tacos: [
      {
        name: 'tacos poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Salads: [
      {
        name: 'salade nicoise',
        price: 19,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Plate: [
      {
        name: 'Plat Mixte',
        price: 45,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Italian: [
      {
        name: 'Spaghetti',
        price: 35,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Pizza: [
      {
        name: 'Pizza poulet',
        price: 30,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Desserts: [
      {
        name: 'keylime pie',
        price: 15,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],
    Drinks: [
      {
        name: 'Soda',
        price: 10,
        image: require('../assets/burger.jpg'),
        details: 'vvvvvvvvvvvvvvvvvvv',
        id: 0,
      },
    ],

    id: 3,
  },
];

export const menuData = [
  { title: 'Sandwiches', special: false, key: 1 },
  { title: 'Burgers', special: false, key: 2 },
  { title: 'Tacos', special: false, key: 3 },
  { title: 'Salads ', special: false, key: 4 },
  { title: 'Plate', special: false, key: 5 },
  { title: 'Italian', special: false, key: 6 },
  { title: 'Pizza', special: false, key: 7 },
  { title: 'Desserts', special: false, key: 8 },
  { title: 'Drinks', special: false, key: 9 },
];

export const specialData = [
  { title: 'LIMITED OFFER', key: 0 },
  { title: 'School nignt', key: 1 },
  { title: 'promotion', key: 2 },
  { title: 'Goute', key: 3 },
];

export const menu = [
  { key: 1, title: 'BEEF' },
  { key: 2, title: 'CHICKEN' },
  { key: 3, title: 'VEGGIE BURGER' },
  { key: 4, title: 'SHARE BOX' },
  { key: 5, title: 'Happy Meals' },
  { key: 6, title: 'Fries' },
  { key: 7, title: 'Sides' },
  { key: 8, title: 'Milkshakes' },
];

// export const filterData2 = [
//   {
//     name: 'burger',
//     image: require('../assets/burger.jpg'),
//     id: '0',
//   },
//   {
//     name: 'Burgers',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/macdo.png',
//     id: '1',
//   },
//   {
//     name: 'Tuna sandwich',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/nandos.png',
//     id: '2',
//   },
//   {
//     name: 'Hotdog',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/pizza.png',
//     id: '3',
//   },
//   {
//     name: 'Chinese',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/pizza6.png',
//     id: '4',
//   },
//   {
//     name: 'Mexican',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate1.png',
//     id: '5',
//   },
//   {
//     name: 'Sea food',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate2.png',
//     id: '6',
//   },
//   {
//     name: 'Chinese Food',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
//     id: '7',
//   },
//   {
//     name: 'Mexican pie',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
//     id: '8',
//   },
//   {
//     name: 'Ocean dish',
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
//     id: '9',
//   },
// ];

// export const menuDetailedData = [
//   {
//     meal: 'Big Mac',
//     price: 70.2,
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate1.png',
//     details: 'McFeast features two 100% fresh beef burger patties that are hot',
//     preferenceTitle: [
//       'Choose your 2 dips',
//       'Choose your 1st drink flavour',
//       'Choose your 2nd drink flavour',
//       'Would you like to add a side?',
//       'Would you Like any extra sauce?',
//     ],
//     preferenceData: [
//       [
//         { name: 'Jalapeno Dip', price: 8.91, checked: false, id: 10 },
//         { name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 11 },
//         { name: 'BBQ Dip', price: 11.99, checked: false, id: 12 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 13 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 14 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 15 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 16 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 17 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 18 },
//         {
//           name: 'Small Strawberry Shake',
//           price: 16.95,
//           checked: false,
//           id: 19,
//         },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 20 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 21 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 22 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 23 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 24 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 25 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 26 },
//         {
//           name: 'Small Strawberry Shake',
//           price: 16.95,
//           checked: false,
//           id: 27,
//         },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 28 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 29 },
//       ],

//       [
//         { name: 'debonairs sauce', price: 8.9, checked: false, id: 30 },
//         { name: 'BBQ Sauce', price: 8.9, checked: false, id: 31 },
//         { name: 'Tikka Sauce', price: 11.9, checked: false, id: 32 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 33 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 34 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 35 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 36 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 37 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 38 },
//         {
//           name: 'Small Strawberry Shake',
//           price: 16.95,
//           checked: false,
//           id: 39,
//         },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 40 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 41 },
//       ],
//     ],
//     minimum_quatity: [2, 1, 1, null, null],
//     counter: [0, 0, 0, 0, 0],
//     required: [true, true, true, false, false],
//     id: 0,
//   },

//   {
//     meal: 'Hand cut chips',
//     price: 29.3,
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
//     details: 'Two 100% fresh beef burger patties that are hot,deliciously',
//     preferenceTitle: [
//       'Choose your 2 dips',
//       'Choose your 1st drink flavour',
//       'Choose your 2nd drink flavour',
//       'Would you like to add a side?',
//       'Would you Like any extra sauce?',
//     ],
//     preferenceData: [
//       [
//         { name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0 },
//         { name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1 },
//         { name: 'BBQ Dip', price: 11.99, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],

//       [
//         { name: 'debonairs sauce', price: 8.9, checked: false, id: 0 },
//         { name: 'BBQ Sauce', price: 8.9, checked: false, id: 1 },
//         { name: 'Tikka Sauce', price: 11.9, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],
//     ],
//     minimum_quatity: [2, 1, 2, null, null],
//     counter: [0, 0, 0, 0, 0],
//     required: [true, true, true, false, false],
//     id: 1,
//   },

//   {
//     meal: 'Chicken Burger',
//     price: 45.7,
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
//     details: '',
//     preferenceTitle: [
//       'Choose your 2 dips',
//       'Choose your 1st drink flavour',
//       'Choose your 2nd drink flavour',
//       'Would you like to add a side?',
//       'Would you Like any extra sauce?',
//     ],
//     preferenceData: [
//       [
//         { name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0 },
//         { name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1 },
//         { name: 'BBQ Dip', price: 11.99, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],

//       [
//         { name: 'debonairs sauce', price: 8.9, checked: false, id: 0 },
//         { name: 'BBQ Sauce', price: 8.9, checked: false, id: 1 },
//         { name: 'Tikka Sauce', price: 11.9, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],
//     ],

//     minimum_quatity: [2, 1, 1, null, null],
//     counter: [0, 0, 0, 0, 0],
//     required: [true, true, true, false, false],
//     id: 2,
//   },

//   {
//     meal: 'Big Mac',
//     price: 50.8,
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
//     details: 'McFeast features two 100% fresh beef burger patties that are hot',
//     preferenceTitle: [
//       'Choose your 2 dips',
//       'Choose your 1st drink flavour',
//       'Choose your 2nd drink flavour',
//       'Would you like to add a side?',
//       'Would you Like any extra sauce?',
//     ],
//     preferenceData: [
//       [
//         { name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0 },
//         { name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1 },
//         { name: 'BBQ Dip', price: 11.99, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],

//       [
//         { name: 'debonairs sauce', price: 8.9, checked: false, id: 0 },
//         { name: 'BBQ Sauce', price: 8.9, checked: false, id: 1 },
//         { name: 'Tikka Sauce', price: 11.9, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],
//     ],

//     minimum_quatity: [2, 1, 1, null, null],
//     counter: [0, 0, 0, 0, 0],
//     required: [true, true, true, false, false],
//     id: 3,
//   },

//   {
//     meal: 'Hand cut chips',
//     price: 29.3,
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
//     details: 'Two 100% fresh beef burger patties that are hot,deliciously',

//     preferenceTitle: [
//       'Choose your 2 dips',
//       'Choose your 1st drink flavour',
//       'Choose your 2nd drink flavour',
//       'Would you like to add a side?',
//       'Would you Like any extra sauce?',
//     ],

//     preferenceData: [
//       [
//         { name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0 },
//         { name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1 },
//         { name: 'BBQ Dip', price: 11.99, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],

//       [
//         { name: 'debonairs sauce', price: 8.9, checked: false, id: 0 },
//         { name: 'BBQ Sauce', price: 8.9, checked: false, id: 1 },
//         { name: 'Tikka Sauce', price: 11.9, checked: false, id: 2 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 0 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 2 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 3 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 5 },
//         { name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6 },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8 },
//       ],
//     ],

//     minimum_quatity: [2, 1, 1, null, null],
//     counter: [0, 0, 0, 0, 0],
//     required: [true, true, true, false, false],
//     id: 4,
//   },

//   {
//     meal: 'Big Mac',
//     price: 70.2,
//     image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate1.png',
//     details: 'McFeast features two 100% fresh beef burger patties that are hot',
//     preferenceTitle: [
//       'Choose your 2 dips',
//       'Choose your 1st drink flavour',
//       'Choose your 2nd drink flavour',
//       'Would you like to add a side?',
//       'Would you Like any extra sauce?',
//     ],
//     preferenceData: [
//       [
//         { name: 'Jalapeno Dip', price: 8.91, checked: false, id: 10 },
//         { name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 11 },
//         { name: 'BBQ Dip', price: 11.99, checked: false, id: 12 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 13 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 14 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 15 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 16 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 17 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 18 },
//         {
//           name: 'Small Strawberry Shake',
//           price: 16.95,
//           checked: false,
//           id: 19,
//         },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 20 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 21 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 22 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 23 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 24 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 25 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 26 },
//         {
//           name: 'Small Strawberry Shake',
//           price: 16.95,
//           checked: false,
//           id: 27,
//         },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 28 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 29 },
//       ],

//       [
//         { name: 'debonairs sauce', price: 8.9, checked: false, id: 30 },
//         { name: 'BBQ Sauce', price: 8.9, checked: false, id: 31 },
//         { name: 'Tikka Sauce', price: 11.9, checked: false, id: 32 },
//       ],

//       [
//         { name: 'Small Coke', price: 8.9, checked: false, id: 33 },
//         { name: 'Small Fanta Orange', price: 8.9, checked: false, id: 34 },
//         { name: 'Small Sprite', price: 11.9, checked: false, id: 35 },
//         { name: 'Small Coke Zero', price: 3.95, checked: false, id: 36 },
//         { name: 'Small Syoney Zero', price: 3.95, checked: false, id: 37 },
//         { name: 'Small Apple Juice', price: 10.95, checked: false, id: 38 },
//         {
//           name: 'Small Strawberry Shake',
//           price: 16.95,
//           checked: false,
//           id: 39,
//         },
//         { name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 40 },
//         { name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 41 },
//       ],
//     ],
//     minimum_quatity: [2, 1, 1, null, null],
//     counter: [0, 0, 0, 0, 0],
//     required: [true, true, true, false, false],
//     id: 5,
//   },
// ];
